<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name="theme-color" content="#07131d"><title>Treasure Rush</title><link rel="stylesheet" href="style.css"></head><body><div id="app">
<header class="topbar"><div class="brand">◆ TREASURE <b>RUSH</b></div><div class="wallet"><span>🪙 <b id="coins">0</b></span><span>💎 <b id="gems">0</b></span><span>💵 <b id="cash">$0.000</b></span></div></header>
<main>
<section id="home" class="screen active"><div class="hero"><div class="hero-copy"><span class="eyebrow">RUN • COLLECT • ESCAPE</span><h1>Treasure<br><em>Rush</em></h1><p>Explore original fantasy worlds, collect treasure and escape the guardian.</p><button class="primary" id="playBtn">▶ PLAY RUN</button></div><div class="scene"><div class="sun"></div><div class="mountain a"></div><div class="mountain b"></div><div class="road"></div><div class="runner"><i class="head"></i><i class="body"></i><i class="leg l"></i><i class="leg r"></i><i class="arm l"></i><i class="arm r"></i></div><b class="orb o1">🪙</b><b class="orb o2">💎</b></div></div>
<div class="quick-grid"><button class="feature-card" id="adBtn"><span>🎬</span><div><b>WATCH AD & EARN</b><small>Completed ad = +20 Coins</small></div><strong>+20</strong></button><button class="feature-card spin" id="spinBtn"><span>🎡</span><div><b>LUCKY SPIN</b><small>20/50/100 coins • 10/30/50 gems • $0.020</small></div><strong>SPIN</strong></button><button class="feature-card" id="refBtn"><span>👥</span><div><b>REFERRAL</b><small>Commission per qualified referral</small></div><strong>$0.050</strong></button><button class="feature-card" id="missionsBtn"><span>🎯</span><div><b>MISSIONS</b><small>Complete daily goals</small></div><strong>OPEN</strong></button></div>
<div class="stats-strip"><div><small>BEST</small><b id="best">0</b></div><div><small>RUNS</small><b id="runs">0</b></div><div><small>LEVEL</small><b id="level">1</b></div><div><small>HEALTH</small><b>♥♥♥</b></div></div></section>
<section id="game" class="screen game-screen"><div class="game-hud"><span>LV <b id="gameLevel">1</b> • <b id="gameMap">Emerald Valley</b></span><span>♥ <b id="health">3</b> 🪙 <b id="gameCoins">0</b> 💎 <b id="gameGems">0</b> ⭐ <b id="score">0</b></span></div><canvas id="gameCanvas"></canvas><div class="touch-controls"><button data-dir="left">◀</button><button data-dir="jump">▲</button><button data-dir="right">▶</button></div><button class="pause" id="pauseBtn">Ⅱ</button><div class="game-help">SWIPE ◀ ▶ • SWIPE UP / TAP ▲ TO JUMP</div></section>
<section id="spin" class="screen modal-screen"><div class="panel spin-panel"><button class="close" data-close>×</button><h2>🎡 Lucky Spin</h2><p class="muted">The selected reward is kept exactly. Claiming requires a completed rewarded ad.</p><div class="wheel-wrap"><div class="pointer">▼</div><canvas id="wheel" width="320" height="320"></canvas></div><div id="spinResult" class="spin-result">Spin to reveal your reward</div><button class="primary" id="spinNow">SPIN NOW</button></div></section>
<section id="referral" class="screen modal-screen"><div class="panel"><button class="close" data-close>×</button><h2>👥 Referral Center</h2><div class="ref-box"><span>Commission</span><b>$0.050</b><small>per qualified referral</small></div><div class="code-row"><input id="refLink" readonly><button id="copyRef">COPY</button></div><button class="primary" id="shareRef">SHARE INVITE</button></div></section>
<section id="missions" class="screen modal-screen"><div class="panel"><button class="close" data-close>×</button><h2>🎯 Missions</h2><div class="mission">🎬 Watch 3 completed ads <b id="adMission">0/3</b></div><div class="mission">🏃 Finish 1 run <b id="runMission">0/1</b></div><div class="mission">🪙 Collect 100 coins <b id="coinMission">0/100</b></div></div></section>
<section id="settings" class="screen modal-screen"><div class="panel"><button class="close" data-close>×</button><h2>⚙️ Settings</h2><button class="setting" id="withdrawBtn">💵 Withdraw</button><button class="setting" id="profileBtn">👤 Profile</button><button class="setting" id="resetBtn">♻️ Reset demo data</button><p class="muted">Minimum withdrawal is <b>$25.00</b>. Real payout validation must be performed on your server.</p></div></section>
<section id="withdraw" class="screen modal-screen"><div class="panel"><button class="close" data-close>×</button><h2>💵 Withdraw</h2><div class="balance">Available <b id="withdrawCash">$0.000</b></div><div class="ref-box"><span>Minimum withdrawal</span><b>$25.00</b></div><input class="field" id="withdrawAmount" type="number" min="25" placeholder="Amount"><select class="field" id="withdrawMethod"><option>Telegram</option><option>USDT</option><option>PayPal</option></select><button class="primary" id="requestWithdraw">REQUEST WITHDRAWAL</button></div></section>
<section id="profile" class="screen modal-screen"><div class="panel"><button class="close" data-close>×</button><h2>👤 Profile</h2><div class="profile"><span>🏃</span><div><b>Runner</b><small>Treasure Hunter</small></div></div><div class="stats-strip"><div><small>COINS</small><b id="pCoins">0</b></div><div><small>GEMS</small><b id="pGems">0</b></div><div><small>RUNS</small><b id="pRuns">0</b></div></div></div></section>
</main><nav class="bottom-nav"><button class="nav active" data-target="home">🏠<small>HOME</small></button><button class="nav" id="navSpin">🎡<small>SPIN</small></button><button class="nav" data-target="missions">🎯<small>MISSIONS</small></button><button class="nav" data-target="profile">👤<small>PROFILE</small></button><button class="nav" data-target="settings">⚙️<small>SETTINGS</small></button></nav></div>
<div id="toast" class="toast"></div><div id="adOverlay" class="ad-overlay"><div class="ad-box"><div class="ad-spinner"></div><h3>Rewarded Ad</h3><p id="adStatus">Waiting for a verified completed-ad event…</p><button id="adDemoComplete" class="secondary">DEMO: COMPLETE AD</button></div></div><script src="game.js"></script></body></html>
